name: binary_interop
version: 0.0.2
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Binary interop is a library that allows load shared libraries, invoke their functions and get access to their data.
homepage: https://github.com/mezoni/binary_interop
dependencies:
  binary_types:
  file_utils: any
  libffi_binaries:
  path: any
  pub_semver: any
  system_info: any
  unsafe_extension:
dev_dependencies:
  unittest: any
